export default {
  aws: "AWS",
  azure: "Azure",
  cloudflare: "Cloudflare",
  digitalocean: "DigitalOcean",
  gitlab: "Gitlab",
  github: "GitHub (Cloud Security)",
  "github-code-security": "GitHub (Code Security)",
  "google-cloud-platform": "Google Cloud Platform",
  "google-workspace": "Google Workspace",
  jumpcloud: "Jumpcloud",
  mezmo: "Mezmo",
  microsoft365: "Microsoft 365",
  supabase: "Supabase",
  vercel: "Vercel",
  zoom: "Zoom",
  custom: "Custom Integrations",
};
